Translink:
  trip_link: https://gtfsapi.translink.ca/v3/gtfsrealtime?apikey=
  position_link: https://gtfsapi.translink.ca/v3/gtfsposition?apikey=
  alerts_link: https://gtfsapi.translink.ca/v3/gtfsalerts?apikey=
  calls_per_key: 1000 # Number of calls that can be made to each API key per day. if uneven, use the lowest value across all keys.
